### ISSUE TITLE
Notes are tied to specific passwords and not to sites or account names

### ISSUE THREAD

**Issue by sknorr** [palant/pfp#100]
I used the notes feature to store information about secret questions for a specific account. Unfortunately the same site also forces me to regularly change passwords. I do that by using the "Generate new password for user name" function in PFP.

Unfortunately, this function will not move over the notes to the new password. This means that as soon as I removed that old password, I had also deleted my answers to these security questions (or whatever other notes there might be).

Off the top of my head, there are a few things that might have been helpful to me:

* Make users aware of the existence of notes before they are deleting a password that has notes associated
* Move notes to newly generated password for same user name
* Allow per-site notes
* Change the definition of an account in PFP: instead of *1 user  name -> 1 password + optional notes*, allow for *1 user name -> 1 or more passwords + optional notes*; this would allow me to delete individual passwords instead of having to delete the entire account

**Comment by palant** [comment]
You are right, notes being lost when converting passwords is an issue that I didn't notice. The first two points you mentioned definitely need to be implemented.

**Comment by palant** [comment]
I'd say that the bug here is fixed. What remains is an enhancement request: allow defining per-site notes. I have my doubts that this one is worth doing, but if you feel strongly about it please create a new issue and we can discuss it there then.

**Comment by sknorr** [comment]
Thank you very much! And no, I don't feel super-strongly about the rest. I think this fixes my use case.
