### ISSUE TITLE
Ability to copy username and website address (and two questions).

### ISSUE THREAD

**Issue by Auronius** [palant/pfp#101]
Good day!
You have made very good password manager! **Thank You!**
Still I miss the ability to copy **username** (marked by red line on the screenshot) and **website address** (blue line) to clipboard, so every time, I have to select them manually, then press Ctrl+С, then click on appropriate browser field, and then press Ctrl+V. This is very inconvenient, especially after autotype usage. 
I am not asking to add autotype option, but could you please add buttons, which allow to copy username and website addresses to clipboard, just like the button, which copies password to clipboard (green rectangle on screenshot)?
[**Screenshot**](https://i.postimg.cc/6p0Sw9mq/Login.jpg)
I miss this ability very much, honestly.

**Also I have two questions.**
1. From [Your article](https://palant.de/2016/04/20/security-considerations-for-password-generators/) I have read, that Easy Passwords have used PBKDF2-HMAC-SHA1 algorithm with 262,144 iterations for password generation. Does **Pain-free Passwords** use the same algorithm, or different? PBKDF2-HMAC-SHA256?
2. From [Here](https://pfp.works/documentation/recovery-strategies/) I have read, that _The backups are encrypted, so this service won’t know which websites you have accounts on._
Which encryption algorithm is used for password database backup encryption?

**Comment by Maryse47** [comment]
> From Your article I have read, that Easy Passwords have used PBKDF2-HMAC-SHA1 algorithm with 262,144 iterations for password generation. Does Pain-free Passwords use the same algorithm, or different? PBKDF2-HMAC-SHA256?

It uses [scrypt](https://github.com/palant/pfp/issues/58) (N=15, r=8, p=1).

> From Here I have read, that The backups are encrypted, so this service won’t know which websites you have accounts on.
> Which encryption algorithm is used for password database backup encryption?

[AES-GCM](https://github.com/palant/pfp/issues/47).


Both were merged in https://github.com/palant/pfp/pull/63

**Comment by palant** [comment]
The big challenge here is adding this functionality without overcrowding the user interface.

One question: why do you need to copy the website name? Is the idea going to the website in question or is there another use for it?

**Comment by Auronius** [comment]
I have a lot of different accounts for forums, web shops, services, and it is impossible for me to remember each website address (around 40). When I try to type web site addresses manually, I often make typos, which lead me to wrong web portals. So I open [this menu](https://i.postimg.cc/9XthNHgp/sites.png), click on necessary web site, then select it and copy the website address just like I have written in the first post. So I have two choices. Either type website addresses manually or perform described sequence, which is inconvenient. Storing websites in bookmarks is not an option, because of privacy reasons.
As for usernames, the same thing, I can not remember all usernames, especially if I have to choose for account registration some specific and unusual username like _Auronius4554_ or _Aur0niusX_ instead of _Auronius_, because _Auronius_ is allready taken by someone. So, I have to manually copy them and paste, which is inconvenient for me.
I am sorry, but I do not think, that adding only two buttons for copying website address and username will ovecrowd the user interface. But it will make PFP much more convenient to use.
@Maryse47, Thank You for detailed answer.

**Comment by palant** [comment]
Ok, the point is visiting the site as I thought. Good to know.

I didn't say that I won't implement this. But it does need some thought.

**Comment by palant** [comment]
Website name is a link now and can be clicked to visit the website.

**Comment by palant** [comment]
I ended up splitting the "copy" menu item into two:

![screenshot](https://user-images.githubusercontent.com/374261/58747910-efbfb500-8471-11e9-995c-d666513af395.png)
