### ISSUE TITLE
Issues on Android in 2.2.0

### ISSUE THREAD

**Issue by sknorr** [palant/pfp#105]
I updated to extension version 2.2.0 and everything works great on desktop (it also looks much nicer, so thanks!). However, on Firefox 68.0b7 on Android, the story is not so great:

* Trying to convert to the new schema took so long that I cancelled it (I have ~100 passwords, which is just a few seconds on desktop but took multiple minutes on mobile before I cancelled it)

* Because the conversion never finished even after killing Firefox multiple times, I uninstalled the extension and reinstalled it. Trying to set up sync, I got an error message after tapping Upload Now, reading "TypeError: browser.browserAction.setBadgeText is not a function."

**Comment by palant** [comment]
The first issue is expected - converting 100 passwords to stored passwords requires generating them first which takes time. The expected time would be below 1 second per password on mobile, but it depends a lot on hardware.

The second is quite problematic as it masks the actual error message. PfP tries to show an exclamation mark on its icon, something that isn't possible on Android.

**Comment by palant** [comment]
With this change the correct error message is being displayed. Also, I verified that sync works correctly on Firefox for Android in principle. So I hope you'll retry once the update is out, maybe the error message will help pinpointing the issue.

**Comment by sknorr** [comment]
Thanks for looking into this and fixing the odd JS error!

> The first issue is expected - converting 100 passwords to stored passwords requires generating them first which takes time. The expected time would be below 1 second per password on mobile, but it depends a lot on hardware.

My phone has a Snapdragon 835 (i.e. a fairly recent upper-end processor), so I don't think it should take multiple minutes unless there is something phenomenally wrong with Firefox beta right now (). Most of my passwords are either PfP 2.0 passwords already or they are stored passwords, so there are maybe 20 PfP 1.0 passwords in there.

----

About the Javascript error, I think I now saw the real error message on a desktop machine: "It seems that remote data has either been tampered with or reset to an older revision." It appears that between my devices, one wasn't updated yet to the new version and synced an old version of the password store. So that seems benign ultimately.

**Comment by palant** [comment]
> It guess that between my devices, one wasn't updated yet to the new version and synced an old version of the password store.

That's strange, it shouldn't happen. The format version has been increased, so older clients shouldn't overwrite data written by newer ones.

**Comment by palant** [comment]
Either way, I guess #103 needs fixing...
