### ISSUE TITLE
User interface window is too big.

### ISSUE THREAD

**Issue by Auronius** [palant/pfp#107]
Good day!
In Chromium browser 76.0.3809.87 the user interface window and program fonts are **too big**. They occupy almost a fifth of the screen. It is very inconvenient. Is it possible to make user interface window smaller? If no, can you add this possibility?
![BIG](https://user-images.githubusercontent.com/13540006/62823999-68dd3600-bba0-11e9-91dc-de6715b219a5.png)

**Comment by palant** [comment]
On your screen, the PfP user interface occupies roughly 15%. Maybe you could help me understand what's inconvenient about it? Does it cover up something? Or is it for purely estetic reasons?

Можете написать по-русски, если так проще.

**Comment by Auronius** [comment]
Это скорее личное предпочтение. Я люблю когда шрифты в системе везде примерно одинаковые, так же как и соотношение размера шрифта с размером окна. В данном случае окно PfP и размер шрифта слишком большие по сравнению с остальными шрифтами. Я немного преувеличил, написав, что это очень неудобно. Просто необычно и не очень приятно на глаз. Поэтому и спросил, есть ли возможность уменьшить размер окна PfP.

**Comment by palant** [comment]
Можно добавить возможность уменьшить размер шрифта, но ширина окна от этого не изменится - разве что высота, да и то не всегда.

**Comment by Auronius** [comment]
Дело в том, что в предыдущих версиях браузера Chromium присутствовала возможность изменения размера окна PfP при помощи браузера. Для этого было достаточно открыть вкладку **Show all passwords** и изменить её масштаб клавишами Ctrl+ и Сtrl-. Однако начиная с версии Chromium 76.0.3809.87 данная возможность (у меня) перестала работать к большому сожалению.

**Comment by palant** [comment]
Предполагаю, что это меняло и размер окна / значков? Не думаю, что я хочу это воссоздавать - только непосредственно размер шрифта.

**Comment by Auronius** [comment]
Позволю себе настоять на добавлении возможности изменять размер окна интерфейса программы. На некоторых сайтах это окно перекрывает поля ввода логина и пароля. Если по каким-либо причинам не работает автозаполнение, то копировать вручную логин и пароль становится неудобно. Нужно кликать чтобы свернуть окно, затем кликать по полю ввода и только потом вставлять логин или пароль.
Вот примеры:
https://drive.google.com/file/d/1GGQybznmqJKUbWe4ZVBqtOz74rvdFD6W/view?usp=sharing
https://drive.google.com/file/d/1QnPID5cGvKnzUbSE2RMjEfqK4QATQH-B/view?usp=sharing

https://drive.google.com/file/d/17pba-jBafmTKNxxrqUhGD10QCacDvMg7/view?usp=sharing
https://drive.google.com/file/d/16ZqqoBneHdmvhxVF4z4pp8JYt52foPhQ/view?usp=sharing

https://drive.google.com/file/d/1A1XD3a5T44El1wi-ctJlD98w7ned7WnS/view?usp=sharing
https://drive.google.com/file/d/1z8ojkeYm9HlCvuNMYhyQ1-OHiwaWRlie/view?usp=sharing

**Comment by palant** [comment]
This change has been rolled back, it’s less than optimal as it was implemented.

**Comment by palant** [comment]
Reopening now that PfP is under development again.
