### ISSUE TITLE
adpworld.de is doing crazy stuff

### ISSUE THREAD

**Issue by sknorr** [palant/pfp#115]
I am opening this issue fully expecting that you probably can't solve it completely but here goes:

1. The page uses company/user/password instead of just user/password.
2. When you try to auto-fill the page, apparently the Log In button is triggered and the login fails. (I enter the company code manually, then click on the User Name field and try to auto-fill.)
3. PfP does not appear to fill in the password at all.

**Comment by palant** [comment]
Yes, that page is really crazy. The developers here don't know that they can use placeholders in input fields. So the "placeholders" shown here are actually text entered into the field (this breaks of course if you try to drag or paste text into the field). Except for the password field - it wouldn't work there (text would be masked), so they display a different field and the real password field stays invisible as long as it isn't focused.

So filling out works fine if you click the password field first. If you didn't then PfP doesn't see a password field at all. It rather assumes that it is one of those forms where you have to fill out the user name first, which it tries to do.

Not sure what I can do here other than tell PfP "don't ignore hidden password fields if you are on adpworld.de" (we already have that for accounts.google.com)...

**Comment by sknorr** [comment]
The page has been redesigned and filling in the login form now works properly. The remaining issue is (1.), i.e. there are three fields instead of two. I am not sure if it's realistically fixable. If not, feel free to close.

**Comment by palant** [comment]
Thank you for letting me know. Yes, filling in additional fields isn't currently something I plan for PfP. I'm just happy that login forms like that are a really rare occurrence…
