### ISSUE TITLE
pfp-web tab opening issues with FF for Android 79.0.5

### ISSUE THREAD

**Issue by PresGas** [palant/pfp#118]
Attempting local install on phone and desktop of releases 2.2.4 and 2.2.3

Sync opens up a tab saying "You will be redirected to the authorization page of your sync provider shortly." but nothing else.

Attempting to show all passwords just closes tab (crashes?), but no other interaction on both desktop and phone.

Let me know if I can provide anything else, primary issues on FF Android as per subject.

**Comment by PresGas** [comment]
Correction on desktop FF for local PfP install. I can view all passwords only once (on new install). Subsequent times, even after restarting the browser, causes tab to just close (crash?). No notification that it crashed.

**Comment by palant** [comment]
PfP 3.0 no longer has sync functionality, sync can be done externally.
