### ISSUE TITLE
Add note icon to popup UI if a password contains a note

### ISSUE THREAD

**Issue by r-a-y** [palant/pfp#128]
It would be nice to include an icon to the popup UI if a given password has a note attached for better usability.

I was re-reading #33 where the note functionality was implemented and one of the initial ideas was to add an icon next to the password:

> There should be one more icon next to the password saying "Notes" in the tooltip. It's probably best to place it on the right side of the password name in the listing so it's clearly different from the password retrieval icons but one still wouldn't click on the delete icon by mistake.

So here's a quick mockup using the existing note icon:

![Mockup](https://user-images.githubusercontent.com/505921/202056591-e0a8dc08-a828-41e9-8bc6-09e031b38bde.png)

Let me know what you think.

**Comment by palant** [comment]
Reopening since PfP development is continuing after all.

**Comment by palant** [comment]
I added the icon on the right side of the entry, simply because otherwise the password titles would no longer be aligned properly if some passwords have notes while others don’t.
