### ISSUE TITLE
Suggestion: option to show master password

### ISSUE THREAD

**Issue by David263** [palant/pfp#132]
I suggest an "eye" icon or some other way to make the master password prompt visible while typing. Some of us are older and cannot type strings accurately without being able to proofread what we type. It should be OUR choice whether to make a password visible, not YOUR choice. By making that decision, we imply that nobody is looking over our shoulder and that we take responsibility for our computer's security.

**Comment by palant** [comment]
Please note that I’m winding down PfP as I can no longer maintain it. Exactly when and how is still to be decided, but I’m definitely not going to implement improvements.

**Comment by palant** [comment]
I guess PfP will live on a bit longer after all, albeit in a quite different form – it requires an external application and stores data in the KeePass format now. So this change has been implemented in PfP 3.0.

This new release is a separate extension, not an update to PfP 2.x. So it will take some time until it is available in all extension stores. It’s there for [Firefox](https://addons.mozilla.org/en-US/firefox/addon/pfp-pain-free-passwords/) now, Chrome review is still ongoing, and I cannot upload to Opera Add-ons as long as PfP 2.x isn’t updated.
