### ISSUE TITLE
Question: how to enter required passwords

### ISSUE THREAD

**Issue by David263** [palant/pfp#133]
Sometimes a password is "required", meaning that it is calculated by a website and must be used to access that website. How do I enter such a required password for a given website, suppressing the usual pfp calculation of the website's password?

**Comment by David263** [comment]
I think this is a valid question, but I think the answer is in the "Generated or stored password?" section in the documentation." Any confirmation? Is this repository being actively maintained?

**Comment by Maryse47** [comment]
There is _Enter stored password_ option in the extension menu which allows you to type any username/password you want and store them permanently (encrypted).
