### ISSUE TITLE
Bug: Error message "Unexpected error: expired_access_token"

### ISSUE THREAD

**Issue by David263** [palant/pfp#134]
There is a small red square above the pfp icon. Clicking it, I see a light pink rectangle around an icon. Clicking the icon, I see "Error: Unexpected error: expired_access_token".

If this is a user error, it needs more explanation of what the user did wrong. If it is a pfp internal error, it should be fixed.

**Comment by Maryse47** [comment]
Maybe you could post a screenshot of what you describe. I don't see any colored squares or rectangles on my system.

**Comment by David263** [comment]
It's too late to take a screenshot. Can't you do a text search over your code to find the error message?

**Comment by Maryse47** [comment]
It's not my code yet I don't see such text in it. I'm not sure if what you describe has anything to do with this extension.

**Comment by David263** [comment]
Fine. Don't believe me. Next time will get a screenshot. Sheesh!

**Comment by David263** [comment]
It happened again. Here is the screenshot. Probably a bug that needs to be fixed?
![PFP](https://user-images.githubusercontent.com/3837238/221438751-da968169-1b2e-48f2-9550-c207f6ba0b6f.png)

**Comment by palant** [comment]
Please note that I’m winding down PfP as I can no longer maintain it. Exactly when and how is still to be decided, but I’m definitely not going to implement improvements.

Dropbox appears to have changed something on their end. Sync is complicated enough that this isn’t trivial to resolve.

**Comment by Maryse47** [comment]
Maybe sync support could be removed altogether (since it's broken right now anyway). Rest of the extension should keep working without further maintenance.

**Comment by David263** [comment]
Maybe. But if the developer is sick of supporting the software, it should die rather than become increasingly out of touch as software and operating systems grow and change in the future. It is pretty bad when people start depending on a password manager and then it malfunctions or dies.

**Comment by Maryse47** [comment]
There is not really much to maintain in offline mode, sync may the only feature with moving parts.

**Comment by palant** [comment]
PfP 3.0 no longer has sync functionality, sync can be done externally.
