### ISSUE TITLE
 Chromium: The operation failed unexpectedly.

### ISSUE THREAD

**Issue by lukethethird** [palant/pfp#139]
Brave Browser Version:
Brave is up to date
[Version 1.59.117 Chromium: 118.0.5993.70 (Official Build) (arm64)](https://brave.com/latest/)
Installed pfp on Firefox and Brave - works on Firefox, has following error on Brave:

The operation failed unexpectedly.
TypeError: Cannot read properties of null (reading 'postMessage')
TypeError: Cannot read properties of null (reading 'postMessage')
    at nativeRequest (chrome-extension://dkmnfejkonkiccilfpackimaflcijhbj/ui/shared.js:1216:8)
    at async Promise.all (index 0)
    at async Proxy.created (chrome-extension://dkmnfejkonkiccilfpackimaflcijhbj/ui/panel/main.js:4596:47)

**Comment by palant** [comment]
The host application does not support Brave. This won’t change either, see https://www.spacebar.news/p/stop-using-brave-browser

**Comment by lukethethird** [comment]
Wladimir,
Thanks for your prompt response, I will no longer use Brave.

Bob

**Comment by lukethethird** [comment]
Wladimir,

Does pop support Vivaldi which is chromium based ?

B

**Comment by palant** [comment]
Yes, Vivaldi is supported.

**Comment by lukethethird** [comment]
Wladimir,

I installed the chrome version in Vivaldi and I am getting a similar error:


The operation failed unexpectedly.
TypeError: Cannot read properties of null (reading 'postMessage')
TypeError: Cannot read properties of null (reading 'postMessage')
    at nativeRequest (chrome-extension://dkmnfejkonkiccilfpackimaflcijhbj/ui/shared.js:1216:8)
    at async Promise.all (index 0)
    at async Proxy.created (chrome-extension://dkmnfejkonkiccilfpackimaflcijhbj/ui/panel/main.js:4596:47)


What do I need to do ?

Bob

**Comment by lukethethird** [comment]
Wladimir,

Disregard the last email,
I
 reread your install instructions and ran the pfp-native-host application to add Vivaldi,

All is working now.


Thanks

Bob
