### ISSUE TITLE
Unable to change the Master Password in PfP 3.1.

### ISSUE THREAD

**Issue by Auronius** [palant/pfp#145]
Good day!
How to change the Master Password (to decrypt the .kdbx database) in PfP 3.1 browser extension? I was unable to find out how.
If it is currently not possible, please add this important option. This is important, because I do not want to make a new database and move all my passwords (more than 50 passwords) to it each time I want to change my Master password. This is **very inconvenient**.

**Comment by palant** [comment]
You can do that with KeePassXC or any other compatible application. PfP doesn’t implement this feature (among quite a few others) to keep things simple.
