### ISSUE TITLE
android compatibility

### ISSUE THREAD

**Issue by CircleCode** [palant/pfp#37]
easy passwords is not presented on the android addons page.
Do you plan to make it compatible with firefox for android?

**Comment by palant** [comment]
This is "nice to have" functionality as far as I am concerned. Mobile isn't my personal priority right now, and Firefox for Android isn't a well-supported platform from what I know. While I didn't look into this yet, I don't think that Web Extensions are on Android yet, and the Add-on SDK doesn't have good user interface integration on Android either.

**Comment by CircleCode** [comment]
I understand and respect this point of view.

However, since data could be synchronized through firefox sync, even a simplified version allowing only to get passwords would be nice for people using both desktop and mobile.
Until this minimalist version exists, I hope I will be able to have the single page version available on my phone to enter generated passwords when I am on mobile

**Comment by palant** [comment]
Sync is not going to be a problem (see #24), but even displaying a page action would be. Either way, I [asked on Mozilla Discourse](https://discourse.mozilla-community.org/t/how-is-one-supposed-to-develop-mobile-add-ons-with-a-ui/10704), maybe there is something I'm missing here.

**Comment by CircleCode** [comment]
thanks for your interest, and your comprehension :-)
I hope there will be some solution, even a minimalist one

**Comment by palant** [comment]
Looking at https://bugzilla.mozilla.org/show_bug.cgi?id=1263005, it seems that page actions are actually supported to some degree in Web Extensions starting with Firefox 50 but documentation hasn't been adjusted yet. That's a start and could actually allow a limited version to work even though `chrome.tabs` API [really isn't supported](https://bugzilla.mozilla.org/show_bug.cgi?id=1260548).

**Comment by CircleCode** [comment]
not sure this would be of any help, but the panel ublock origin [1] shows in desktop is implemented as a new tab in mobile. Don't know how they achieve it, but this could be a path.

[1]: https://github.com/gorhill/uBlock

**Comment by palant** [comment]
Ok, I've hit https://bugzilla.mozilla.org/show_bug.cgi?id=1300807 immediately - page actions don't seem to be usable just yet. I've also noticed https://bugzilla.mozilla.org/show_bug.cgi?id=1300808 which is somewhat less critical. Altogether, WebExtensions don't seem to be ready on Android, not even for a very limited solution.

uBlock is escaping the Add-on SDK sandbox and going for low-lever browser APIs directly. As I mentioned on Discourse, this is a last resort but not a future-proof solution.

**Comment by CircleCode** [comment]
thanks at least for trying so quickly (I ❤️ open source!)
for uBlock solution, I was hoping they were using another way, but as you said this is not future proof at all
So I supose this feature will remain open for history until some progress is done on firefox for android side, or until someone comes with some magical solution on discourse…

**Comment by palant** [comment]
Yes, I think that at the current stage investing effort into Firefox on Android makes little sense - the time would be better spent packaging up https://palant.github.io/easypasswords/online.html as an Android app and adding syncing to it so that the process isn't quite as manual.

**Comment by CircleCode** [comment]
Maybe this page could be packgd as a web app with the following features:
* auto-update
* auto-retrieve up-to-date password elements (thanks to #24 or to a service like Dropbox and others)

This would be sufficient to allow mobile users to use their passwords on their mobile

**Comment by palant** [comment]
There is a fully featured web client under https://pfp.works/webclient/ now, and there will be downloadable packages for it once the next release is out. That's a good first step towards an Android client. Usability can be improved in a few places, particularly #52 should help quite a bit. And getting #24 done is a must-have.

**Comment by r-a-y** [comment]
Thanks for this, @palant.

Worth mentioning is that you can use the Easy Passwords addon on Firefox for Android.  I've been using this already with success.

**Comment by palant** [comment]
I know. There are some minor issues (#60 and #61) that I hope to still get fixed before the next release, but for most part it works just fine. Unfortunately, not a viable option for most people.

**Comment by charliemb2** [comment]
I was able to install Firefox for Anroid today, just for the purpose of installing and trying Easy Passwords based on this thread.  To my surprise, I found Pain-Free Passwords instead.  I installed it successfully.  Will it work or should I attempt to find Easy Passwords?   -Thanks

**Comment by palant** [comment]
Pain-Free Passwords is the new name of the Easy Passwords extension.

**Comment by charliemb2** [comment]
Today I installed PfP on Android.  Last night I installed on Windows 7.
Today I created a test password in Android and synced to Drive.
Tonight on Windows 7 I established the same masterpassword for the first time and synced to Drive in hopes of using that same test password.    **This failed.**   The sync status is good, but I get a "No passwords yet" message even after the sync.

User error?  Bug?  Feature?

BTW, this was like simulating buying a new desktop computer and syncing from whatever is on Drive.  So I think this should have worked.   No?

Thanks

**Comment by palant** [comment]
It should have worked, but spamming an unrelated issue is not the solution. Please open a new issue for this, then I can ask follow-up questions.

**Comment by charliemb2** [comment]
Sorry.  Please delete.

**Comment by Noitidart** [comment]
We should use react-native and create an app out of this for iOS and Android.

**Comment by palant** [comment]
Cordova also allows adding native code if needed. However, given how messed up the Apple ecosystem is, I don't expect us to target iOS any time soon.

**Comment by Noitidart** [comment]
Ohh cool re native code on Cordovoa.

I totally agree with you, Apple ecosystem is absolutely trash. Trying to get an app submitted to the store requires all kinds of ridiculous leg work.

**Comment by mekineer** [comment]
Kiwi web browser works with Chrome extensions.

**Comment by David263** [comment]
If you made a Web-based solution to this issue that could decrypt the pfp passwords locally for manual use, perhaps using Ajax if necessary, then desktop users of pfp could still access their passwords on ANY other device, including iOS and Android. Just one page, running in almost any browser, could do the job without Web extensions or anything else fancy. Manual copying and pasting of passwords is much better than nothing. Just my opinion, but I hope you agree.

**Comment by palant** [comment]
As of PfP 3.0, we now use KeePass database format. Which means: any KeePass-compatible app can be used on Android, I no longer have to provide one.
