### ISSUE TITLE
Publish data format specifications

### ISSUE THREAD

**Issue by CircleCode** [palant/pfp#38]
the password generation mechanism and the exported file format shoud be specified so that other "clients" could be written, even in other language.

One could imagine
- android client with custom keyboard like for example [keepass2android](https://play.google.com/store/apps/details?id=keepass2android.keepass2android) - this would address #37 
- linux client like [pass](https://www.passwordstore.org)

and others

**Comment by palant** [comment]
Given that this extension is still very young and doesn't have too many users at this point, I'm very reluctant to publish specifications. In particular, the data formats are still likely to change. They did so only recently when the 1.1.0 release introduced password revisions, and I think that there will be at least one small change again at some point (renaming password types).

Thank you for pointing me to keepass2android, I didn't consider soft keyboards when thinking about Android integration points. Unfortunately, the way I understand [the documentation](https://developer.android.com/reference/android/view/inputmethod/InputConnection.html) a soft keyboard won't be able to tell which website the input fields belongs to.

**Comment by CircleCode** [comment]
I understand your arguments against too early specification, this can be marked as milestone 2.0 for example (or just as "future" tag).

for keepass2android, IIRC, the soft keyborad is only here to prevent password steal when they are in the clipboard.
The workflow it suggests is as follows (simplified version):
1. use the "share" feature of android to share current page with keepass2android
    under the hood, keepass2android remembers the "active website" is the one you just "shared" with it
2. use the custom key on the keepass2android keyboard to trigger its action
    keepass2android opens a popup relative to the last known "active website"
3. in the opening popup, choose between "username" and password
    keepass2android simulates the input of the selected value at the cursor position
In case you would see it in action, this process is well shown in https://youtu.be/rDV7JQsN0pM?t=87

**Comment by palant** [comment]
Documentation has been added: https://github.com/palant/pfp/wiki
