### ISSUE TITLE
[2.0] Username is copied with spaces before and after

### ISSUE THREAD

**Issue by FedericoYundt** [palant/pfp#71]
I noticed that when I copy username from pfp popup it contains spaces before and after it: `[space]username[space]`. Pasting it into some login forms can cause breakages which can be non obvious to spot. Also copying it back to pfp can create mess. It doesn't happen when copying usernames from "All passwords" page.

Firefox 58 / Linux

**Comment by FedericoYundt** [comment]
It's not always reproducible. It happens mostly when your username is something like `aaa@bbb.com` and you have to do triple click to select it all.

**Comment by palant** [comment]
Yes, I've seen this as well. Removing spaces from the template is awkward but I guess that's what I need to do.
