### ISSUE TITLE
Add "blacklist characters" option

### ISSUE THREAD

**Issue by FedericoYundt** [palant/pfp#72]
Some sites have different special characters allowance. When site doesn't allow peculiar character which is included in your generated password the only option we have is to disable special characters altogether. I propose to add "blacklist characters" option in password creation popup where we can specify one or more characters which can't be part of generated password. Alternatively this can be used as additional _defense-in-depth_ technique for preventing masterpassword recovery.

Technically it can work by omitting specified characters in generated password and add the next one (password_length+1) instead to achieve same password length.

**Comment by palant** [comment]
I'd rather not to add too much complexity here. So far whenever I encountered a website like this, disabling special characters altogether worked. If you have a site where it doesn't, please let me know.

Note that your typical 16 characters password has 86 bits of entropy even without special characters which is more than enough.

**Comment by FedericoYundt** [comment]
I don't know site which requires special characters but doesn't support full special characters set but probably such sites exist and it will be problem.

If you think it's unnecessary feel free to close this.

**Comment by palant** [comment]
Maybe such sites exists and I just never came across them, there are all kinds of crazy sites out there. So far the default character sets of PfP worked surprisingly well, and I'd rather stick with them as much as possible. If nothing else, they make password recovery without backup easy - so far it's either all character sets or all but special characters for me.
