### ISSUE TITLE
not work when  dom.workers.enabled=false

### ISSUE THREAD

**Issue by ad1862** [palant/pfp#75]
In my FF workers are disabled because of security concerns. Version 1 worked without problems, but version 2 now does not work. Is it possible to use this extension without enabling workers?

FF 56.0.2

**Comment by FedericoYundt** [comment]
It seems that pref is being removed ind next ESR: https://bugzilla.mozilla.org/show_bug.cgi?id=1434934

**Comment by ad1862** [comment]
_"Worker should be always enabled."_
another "improvement" in >=57. I hope that this pref can be avoided.

**Comment by palant** [comment]
> In my FF workers are disabled because of security concerns. 

What kind of security concerns? Webpages not blocking everything on a heavy operation shouldn't normally be a concern. That's exactly what PfP is doing - password generation is a very heavy operation, it should be running in background. The only reason we (usually) avoided workers in the previous version was that PBKDF2 is implemented by the browser and the browser took care of running this operation in background.

Definitely "wontfix" and I'd strongly advise against messing with that kind of prefs.

**Comment by palant** [comment]
Seeing that you are still on Firefox 56, I guess I understand the concern. Frankly, disabling browser functionality won't keep you safe on an outdated browser however. A browser is a highly complex beast, and you cannot pinpoint the complexity to a single component - it's rather the web platform as such being complex. Installing updates is the only way to stay safe. Well, other than using [lynx](https://en.wikipedia.org/wiki/Lynx_(web_browser)) that is.
