### ISSUE TITLE
Web client needs a progress indicator when loading

### ISSUE THREAD

**Issue by Noitidart** [palant/pfp#76]
At here - https://pfp.works/webclient/ - using Firefox, when I click "Understood let me try it now", it shows blank between the header and footer.

**Comment by palant** [comment]
It takes a while to download, this page is just as heavy as the extension itself - around 500 kB (mostly due to the zxcvbn library). Which doesn't mean that some kind of progress indicator isn't desirable.

**Comment by Noitidart** [comment]
Oooh shoot. Excuse that. I went back to the tab and it's there! Thanks for leaving this open for me to close. <3

**Comment by palant** [comment]
I allowed myself to reopen this issue and to change the title - this definitely needs addressing, you probably aren't going to be the only one confused.

**Comment by Noitidart** [comment]
Oh cool thanks! Apologies for the extra work haha
