### ISSUE TITLE
Firefox ESR: fails to generate password - worker error

### ISSUE THREAD

**Issue by FedericoYundt** [palant/pfp#78]
When trying to generate password it fails with `worker error` message. In browser console there is info about `TypeErrror: invalid arguments` in `scrypt.js` line 1205: `var dk = new Uint8Array(length);`.

Tested with Firefox ESR 52.6 on Debian stable. **Fresh profile**.

**Comment by palant** [comment]
Sounds like the same issue I had to fix for Edge: https://github.com/palant/pfp/commit/1506d6c886b2162b01d81510f956464ecf5d109a. Guess I'll need this change after all, will have to test.

**Comment by palant** [comment]
PfP 2.0.2 is out, it should work now.

**Comment by FedericoYundt** [comment]
Works great, thx!
