### ISSUE TITLE
Nextcloud sync support

### ISSUE THREAD

**Issue by rugk** [palant/pfp#85]
I'd really not trust Dropbox or Google with my passwords, even when encrypted. There is still some meta data, e.g. when one creates passwords.

In any case, it would be nice if you could add NextCloud as a sync option.

**Comment by palant** [comment]
I looked into it briefly, and it seems that the APIs offered by NextCloud out of the box are WebDav and OCS. According to documentation, both expect authorization to happen either via username:password combination or via a session cookie. Neither would be a good option for PfP. However, it seems that there is an undocumented (!) OAuth2 authorization flow as well. Still no scope limiting from what I can tell, but at least something one can work with.

As to the actual APIs, OCS is the more convenient API but seems to expose auxiliary functionality only. So WebDav it is. It appears that conflict prevention works similarly to Google Drive, meaning sending `If-Match: <ETag>` header with the request. This isn't properly documented however. I might play around with the demo instance at some point but given the sad state of the documentation this isn't really a priority.

**Comment by rugk** [comment]
Yeah, AFAIK OAuth2 is quite new.

**Comment by palant** [comment]
https://github.com/nextcloud/server/pull/4704 - almost a year.

**Comment by mekineer** [comment]
I had not discovered PFP until someone mentioned it to me.  I've been using Keepass2Android, which is able to connect with NextCloud.

**Comment by pwFoo** [comment]
I use Keeweb which also support different backends and webdav too.

**Comment by palant** [comment]
Yes, Keeweb fails to account for concurrent uploads, meaning that one device might end up overwriting changes made by another. So I guess that they have the same issues I listed in https://github.com/palant/pfp/issues/85#issuecomment-374531794 but chose to ignore them.

**Comment by palant** [comment]
PfP 3.0 no longer has sync functionality, sync can be done externally.
