### ISSUE TITLE
cannot link to google drive

### ISSUE THREAD

**Issue by ImBehindSevenProxies** [palant/pfp#89]
Hello, thanks for the extension, i have a problem : "Firefox can’t establish a connection to the server at localhost:37602."

https://www.youtube.com/watch?v=OTsuqSVGmZM

not sure if it's because i'm using an account container for google?

thanks you

**Comment by palant** [comment]
I'm sorry but what does this have to do with PfP?

**Comment by ImBehindSevenProxies** [comment]
Pfp cannot be synced with google drive because of a bug

**Comment by palant** [comment]
Yes, it should be because of containers. I'll have a look.

**Comment by ImBehindSevenProxies** [comment]
Sorry it is working now if i don't use Account container.

**Comment by palant** [comment]
I understand this, but I want to see whether this can work with containers - or whether Firefox has to fix their APIs maybe.
