### ISSUE TITLE
Sync failed on Win7 after first syncing on Android

### ISSUE THREAD

**Issue by charliemb2** [palant/pfp#90]
Thanks for all of your work on this wonderful extension.

Last night I installed PfP on Windows 7, but did not go so far as to set a master password.
Today I installed PfP on Android and created a test password.  I also synced to Drive.

Tonight on Windows 7 I established the same masterpassword for the first time and synced to Drive in hopes of using that same test password.  This failed.  The sync status is good, but I get a "No passwords yet" message even after the sync.

User error? ... Bug? ... Feature?

BTW, this was like simulating buying a new desktop computer and syncing from whatever is on Drive. So I think this should have worked. No?

Thanks

**Comment by charliemb2** [comment]
Checking Google drive...  I don't know what to look for but the sync file isn't jumping out at me.  Where should the sync file reside, and what is the file name?

If there is no sync file, we may have found the source of this issue.

**Comment by palant** [comment]
The sync file isn't visible on Google Drive (unavoidable unfortunately), you can only see PfP under Applications - it will show you that some data is stored.

**Comment by charliemb2** [comment]
Update: I was able to replicate the situation on Linux.  After installing PfP in Firefox I synced with Google Drive and the behavior is the same as with Win7.   I see no passwords.

**Comment by palant** [comment]
PfP 3.0 no longer has sync functionality, sync can be done externally.
