### ISSUE TITLE
Create a basic PfP app for Android

### ISSUE THREAD

**Issue by fhd** [palant/pfp#91]
Didn't want to revive #37 (which seems to have a broader scope) for this, so here's a dedicated issue for working on a PfP app for Android, something I'd like to tackle.

As briefly discussed on IRC, the idea is to use Apache Cordova to reuse as much code as possible. This'll also pave the way towards an iOS app, but I'll focus on Android at first, since that's what I mostly care about :smile:

Scope-wise, I'll aim for feature parity with the web client first.

**Comment by sknorr** [comment]
Fyi, there is a native Android password generator that already looks a lot like PfP but unfortunately creates incompatible passwords: https://secuso.aifb.kit.edu/english/486.php

**Comment by Maryse47** [comment]
It creates incompatible passwords because it doesn't share anything with PfP except same "deterministic password manager" concept. There are dozens of password managers like this.

**Comment by gotgot1995** [comment]
> Didn't want to revive #37 (which seems to have a broader scope) for this, so here's a dedicated issue for working on a PfP app for Android, something I'd like to tackle.
> 
> As briefly discussed on IRC, the idea is to use Apache Cordova to reuse as much code as possible. This'll also pave the way towards an iOS app, but I'll focus on Android at first, since that's what I mostly care about smile
> 
> Scope-wise, I'll aim for feature parity with the web client first.

Hi @fhd , great idea ! I'm quite interested in this Android project and I'd be ready to contribute. I saw you forked the PfP repository. Have you started the project on your own ?

**Comment by fhd** [comment]
@gotgot1995 No, unfortunately I didn't get around to it so far. If you want to take a shot at it, feel free to go ahead.

**Comment by Noitidart** [comment]
Looks like in Android 8+ and iOS 10+ we can use autofill, just learned this - https://github.com/buttercup/buttercup-mobile

**Comment by palant** [comment]
Nope, it says that autofill works in Safari, so iOS-only.

**Comment by gotgot1995** [comment]
Hi @fhd , just wanted to revive the subject 😄.

I'm really up to contribute on a port of PfP to Android (or at least a standalone electron.js app). Let me know of your availability so we can start working on a roadmap.

**Comment by palant** [comment]
Sorry @gotgot1995, I think that @fhd is too busy with other stuff. He has a company to lead. :smile: 

I looked into vue-native and similar approaches for this port but eventually concluded that it's too much effort. So let's stick to the original plan and use Cordova. I plan a new release next week after which I should hopefully have some time to look into it again.

**Comment by PresGas** [comment]
Came over from #117 . I look forward to this release and appreciate the work!

**Comment by gotgot1995** [comment]
Hi everyone. Any news on the subject? 😅

**Comment by palant** [comment]
Not from my end unfortunately.

**Comment by palant** [comment]
As of PfP 3.0, we now use KeePass database format. Which means: any KeePass-compatible app can be used on Android, I no longer have to provide one.
