### ISSUE TITLE
Better UI

### ISSUE THREAD

**Issue by roguh** [palant/pfp#94]
Are there any plans for improving the user interface?

Although I think the interface is well thought-out, I think it could still use some graphical improvements. The only actual issue I have is that the addon does not work well on Firefox on Android; the door hanger is actually opened in another tab so everything looks too small. 

I plan to work on some improvements I have in mind, including on fixing this issue on Android. I'm posting this issue to keep track of any progress on this.

**Comment by roguh** [comment]
Here are some screenshots:

![screenshot_20180821-220338](https://user-images.githubusercontent.com/6373447/44442359-ee7e6500-a58e-11e8-9159-675eff3aac52.png)
![screenshot_20180821-220252](https://user-images.githubusercontent.com/6373447/44442375-08b84300-a58f-11e8-89a6-fde2316fe95d.png)

**Comment by palant** [comment]
The scaling seemed fine to me when I tried the extension on Firefox for Android, but I'll try again to see whether I can reproduce this issue. In general, more significant UI changes are planned. In particular, I want a tool selection on the left side indicating where you are right now - search, password list or sync settings.

**Comment by adrium** [comment]
What do you think about adrium/easypass ?

**Comment by palant** [comment]
I suggest that you stop spamming. This is largely about the way the user interface looks in Firefox Mobile - which is the only mobile browser to support extensions. You are free to do your Chrome-only fork, but please don't add noise to my issues.

**Comment by roguh** [comment]
Pardon me  Feel free to delete this issue

**Comment by roguh** [comment]
Wait, I thought you were calling the issue spam, not the comment.

As an update, I think #91 might be a more general fix. I only want a way to access this password manager on mobile.

On another note, the Firefox UX is almost ok. When I tap on any text input, the display zooms in to a reasonable level.

**Comment by roguh** [comment]
This was most recently reproduced on Firefox Beta 63.09b on Android.

**Comment by palant** [comment]
Sorry about it, when I talked about spam I meant https://github.com/palant/pfp/issues/94#issuecomment-425643201 of course.

**Comment by javenschuetz** [comment]
my 2 cents on the UI is that some minimal keyboard shortcuts would be an important addition. IIRC, bitwarden uses ctrl+shift+L to auto-fill and it makes a huge difference in usability. I don't really care about a fancy ui besides this.

(Pardon me if the shortcut already exists, I spent some time trying to find it earlier today and even grepped through the codebase very briefly)

**Comment by palant** [comment]
Landed a massive change refactoring the panel on top of the Vue.js framework. This is an important prerequisite for UI improvements as the complexity was getting prohibitive here. Also, some UI improvements have been implemented in this step already, e.g. quite a few UI pieces are modal overlays now.

> Pardon me if the shortcut already exists

See https://github.com/palant/pfp/issues/43#issuecomment-450913930

**Comment by palant** [comment]
Forgot to reference this issue in https://github.com/palant/pfp/commit/087a285c56839964e8b1924c8a9068ef56129b53, it belongs here.

**Comment by palant** [comment]
Here is how it looks now:

![screenshot](https://user-images.githubusercontent.com/374261/58736787-640d4080-83ff-11e9-9565-018904edd1b1.png)

**Comment by palant** [comment]
And slightly differently now after addressing #101 (website name is a link):

![screenshot](https://user-images.githubusercontent.com/374261/58745066-e9b6dd80-844b-11e9-9286-d2b638b47afc.png)

**Comment by palant** [comment]
The scaling issue as reported initially should be fixed as well now.

**Comment by palant** [comment]
Unfortunately, I don't see any way to improve display of options, this one is controlled by Firefox itself. When viewing options within PfP user interface, it works fine however.

**Comment by jotaf98** [comment]
The new UI looks great! When can we expect it to land?

Perhaps more importantly, does it fix the scaling issues in Firefox for Android? The addon is pretty functional there, but having to zoom in PfP's overlay on an otherwise mobile-friendly page to click tiny buttons is not great.

**Comment by palant** [comment]
As I said above:

> The scaling issue as reported initially should be fixed as well now.

I hope to have the release ready within two weeks, there are still two major changes outstanding.

**Comment by jotaf98** [comment]
Alright, sorry I missed that part. Glad to hear it! Thanks for the amazing password manager by the way!

**Comment by Auronius** [comment]
> I hope to have the release ready within two weeks, there are still two major changes outstanding.

I already merged all my passwords to PfP. I am waiting for new release with updated interface.
